# KubeArmor is an open source software that enables you to protect your cloud workload at run-time.
# To learn more about KubeArmor visit:
# https://www.accuknox.com/kubearmor/

apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-cve-2024-3094-xz-utils-v5-6-backdoor
spec:
  tags: ["CVE", "CVE-2024-3094", "remote-code-execution", "backdoor"]
  message: "Alert! Blocked a process from using compromised versions of xz and liblzma (v5.6.0, v5.6.1)."
  nodeSelector:
    matchLabels:
      # regex matching name of the VM that you want to secure
      kubearmor.io/hostname: xz-exploit-demo-vm
  file:
    # this will match any file containing liblzma.so.5.6.0 and block
    # whenever a process tries to access it
    severity: 5
    matchPatterns:
    - path: "/**/liblzma.so.5.6.0.*"
    - path: "/**/liblzma.so.5.6.1.*"
    matchPaths:
    - path: /usr/lib/x86_64-linux-gnu/liblzma.so.5.6.0
    - path: /usr/lib/x86_64-linux-gnu/liblzma.so.5.6.1
    - path: /usr/lib/liblzma.so.5.6.0
    - path: /usr/lib/liblzma.so.5.6.1
  action: Block
